#!/bin/bash

# --Wakuu--
# is a script for creating a C like project structure and a Makefile

# Manual:
#
# wakuu -<language> -p <projectName>		-> creates a new <language> project named <projectName>, based on the <language> different project structure
# wakuu -<language> -c <className>			-> creates a new class of the language in given directories
#
#
#
#
#

function printManual() {
	echo "---Manual---"
	echo "wakuu is a small bash script for creating a project structure for different languages"
	echo ""
	echo "How to use:"
	echo ""
	echo "wakuu -<lang> -p <name>		-> creates a new project of language <lang> named <name>"
	echo "wakuu -<lang> -c <name>		-> creates a new class of language <lang> with name <name> in given directories"
	echo "------"
	echo "Current supported languages:"
	echo "c, cpp, java, python, bash, html, latex"
	echo "------"
}

function createClassC() {
	className=$1
	CWD=$(pwdx $$)

	# Check if C project already exists
	if [ ! -f "Makefile" ]; then
		echo -e "C project does not exist\nUse -p to create the project first"
		printManual
		return
	fi

	headerContent="#pragma once\n\n"
	srcContent="#include \"$className.h\"\n\n"
	

	#create files and append to them
	cd src/ && touch "$className.h" && touch "$className.c"

	echo -e $headerContent >> "$className.h"
	echo -e $srcContent >> "$className.c"
	cd ..
}

function createClassCPP() {
	className=$1
	CWD=$(pwdx $$)

	echo "C++"
}

function createClassJava() {
	className=$1
	CWD=$(pwdx $$)

	classContent="public class $className \n{\n\tpublic $className() {\n\t\n\t}\n}"

	echo -e $classContent >> "$className.java"
}

function createClassPython() {
	echo "Python"
}

function createClassHTML() {
	echo "HTML"
}

function createClassBash() {
	echo "bash"
}

function createClassLatex() {
	echo "Latex"
}

# Functions for creating a project structure based on the given language
# Current support for:
# -c
# -cpp
# -java
# -python
# -html
# -bash
# -latex
function createStructureC() {
	#create project structure:
	# $name/
	# |
	# |---src/
	# |		|-main.c
	# |---obj/
	# |		|-main.o
	# |---bin/
	# |		|-$name
	# |
	# |-Makefile

	#create directory with projectName
	name=$1
	mkdir $name
	#go into it
	cd $name

	#create subdirectories
	mkdir src
	mkdir obj
	mkdir bin

	#append content to files
	makefileContent="PROJECT\t:= $name\nCC\t:= gcc\nCFLAGS\t:= -Wall -Werror \n#-Wextra -pedantic\n\nSRC\t:= ./src\nBIN\t:= ./bin\nOBJ\t:= ./obj\n\nOBJECTS\t:= main.o\n\n.PHONY: default\ndefault: \$(OBJECTS)\n\t\$(CC) -o \$(BIN)/\$(PROJECT) \$(OBJ)/$^\n\n%.o: \$(SRC)/%.c\n\t\$(CC) -c $< -o \$(OBJ)/\$@ \$(CFLAGS)\n\n\nclean:\n\trm \$(OBJ)/*.o \$(BIN)/\$(PROJECT)"

	mainContent="#include<stdio.h>\n\nint main(int argc, char** argv) {\n\treturn 0;\n}"

	#create and append to files
	echo -e $makefileContent >> Makefile
	echo -e $mainContent >> src/main.c
}

function createStructureCPP() {
	#create project structure:
	# $name/
	# |
	# |---include/
	# |
	# |---src/
	# |		|-main.c
	# |---obj/
	# |		|-main.o
	# |---bin/
	# |		|-$name
	# |
	# |-Makefile

	#create directory with projectName
	name=$1
	mkdir $name
	#go into it
	cd $name

	#create subdirectories
	mkdir bin
	mkdir include
	mkdir src
	mkdir obj

	#append content to files
	makefileContent="PROJECT\t:= $name\nCC\t:= g++\nCFLAGS\t:= -Wall -Werror \n#-Wextra -pedantic\n\nINC\t:= ./include\nSRC\t:= ./src\nBIN\t:= ./bin\nOBJ\t:= ./obj\n\nOBJECTS\t:= main.o\n\n.PHONY: default\ndefault: \$(OBJECTS)\n\t\$(CC) -o \$(BIN)/\$(PROJECT) \$(OBJ)/$^\n\n%.o: \$(SRC)/%.cpp\n\t\$(CC) -c $< -o \$(OBJ)/\$@ \$(CFLAGS)\n\n\nclean:\n\trm \$(OBJ)/*.o \$(BIN)/\$(PROJECT)"

	mainContent="#include <iostream>\n\nint main(int argc, char **argv) {\n\tstd::cout << \"Hello World\" << '\\\n';\n\treturn 0;\n}"

	#create and append to files
	echo -e $makefileContent >> Makefile
	echo -e $mainContent >> src/main.cpp
}

function createStructureJava() {
	name=$1
	mkdir $name
	cd $name

	mainClass="public class Main {\n\tpublic static void main(String[] args) {\n\t\tSystem.out.println(\"Hello World\");\n\t}\n}"

	echo -e $mainClass >> Main.java
}

function createStructurePython() {
	echo "Python"
}

function createStructureHTML() {
	echo "HTML"
}

function createStructureBash() {
	#create project structure
	# $name
	# |
	# |---$name.sh
	# |

	#create directory with project name
	name=$1
	mkdir $name
	#go into it
	cd $name

	#content of bash file
	bashContent="#!/bin/bash\n\n"

	#create bash file and append content
	echo -e $bashContent >> $name.sh
}

function createStructureLatex() {
	name=$1
	mkdir $name
	cd $name

	# Content of .tex file
	texContent=""

	makefileContent="default:="

	echo -e $texContent >> $name.tex
	echo -e $makefileContent >> Makefile
}

lang=$1
tag=$2
name=$3

CWD=$(pwdx $$)

if [ "$tag" = "-p" ]; then
	# Create project structure
	# Check for language
	case "$lang" in
	"-c")		createStructureC $name ;;
	"-cpp")		createStructureCPP $name ;;
	"-java")	createStructureJava $name ;;
	"-python")	createStructurePython $name ;;
	"-html")	createStructureHTML $name ;;
	"-bash")	createStructureBash $name ;;
	"-latex")	createStructureLatex $name ;;
	*)	echo "Not a supported language"
		printManual
		;;
	esac
elif [ "$tag" = "-c" ]; then	
	# Create a class
	# Check in which language
	case "$lang" in
	"-c")		createClassC $name ;;
	"-cpp")		createClassCPP $name ;;
	"-java")	createClassJava $name ;;
	"-python")	createClassPython $name ;;
	"-html")	createClassHTML $name ;;
	"-bash")	createClassBash $name ;;
	"-latex")	createClassLatex $name ;;
	*)	echo "Not a supported language"
		printManual
		;;
	esac
else
	echo "Wrong use"
	printManual
fi
